### ISSUE TITLE
Conflict with Flashcord theme

### ISSUE THREAD

**Issue by LunarcatOwO** [MiniDiscordThemes/SettingsIcons#9]
um, so after u updated and released it, it seems to break other themes, I don't know why

**Comment by Saltssaumure** [comment]
Which other themes does it break?

**Comment by LunarcatOwO** [comment]
Lightcord was broken with it, it broke alot of the features and some of the overlays, it also broke the background sorry for responding so late, I rarely cheak github

**Comment by Saltssaumure** [comment]
No worries on the reply speed. I'm gonna have to ask for either the link to the theme, or the theme file itself, as I cannot find a theme called "Lightcord" by search.

**Comment by LunarcatOwO** [comment]
> No worries on the reply speed. I'm gonna have to ask for either the link to the theme, or the theme file itself, as I cannot find a theme called "Lightcord" by search.

Sorry I mean flashcord lol

https://github.com/SiriusBYT/Flashcord

That's the link

**Comment by Saltssaumure** [comment]
Skimming through the files I can't say for sure where the conflict is. It would help me find the problem if you could give me:
- the client mod you're using (Vencord/Vesktop/browser extension?)
- how you installed Flashcord and which files in particular
- specific descriptions and/or screenshots of what's broken

**Comment by LunarcatOwO** [comment]
Vesktop
through vencord's online themes tab
What happens when I add the settings icon theme:
![image](https://github.com/MiniDiscordThemes/SettingsIcons/assets/54731257/8eb24793-c4fa-43a5-ba01-965c0d1628c8)
![image](https://github.com/MiniDiscordThemes/SettingsIcons/assets/54731257/8468c76b-10e3-403e-9c47-03fe193fed25)
How it looks normally:
![image](https://github.com/MiniDiscordThemes/SettingsIcons/assets/54731257/5ae47e48-2bd4-4dab-951f-80723b8beae6)
![image](https://github.com/MiniDiscordThemes/SettingsIcons/assets/54731257/1a6fea81-da33-4128-adcf-326262ee858f)

I only included parically the image as there are chats I would not like to show

**Comment by Saltssaumure** [comment]
I think this might not be possible to fix, since both themes depend heavily on one feature that fundamentally clashes with each other. Sorry about that.

**Comment by LunarcatOwO** [comment]
It worked with an older version of this theme like the version before the version when this issue I opened was
